schema_version = "1.0.0"

id = "arrietty"
version = "0.3.0"
name = "Arrietty"
tagline = "Enter Blender scenes through a SteamVR headset"
maintainer = "ysk424"
type = "add-on"
website = "https://github.com/ysk424/Arrietty"

blender_version_min = "5.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

[build]
paths_exclude_pattern = [
  "__pycache__/",
  "/.git/",
  "/.gitignore",
  "/.vscode/",
  "/.idea/",
  "/tests/",
  "/test_data/",
  "/*.zip",
]
